__author__ = 'samgu'

VALUE = 'value'
DISPLAY = 'display'
NOPAY = 'no_pay'
PAID = 'paid'
HANDLING = 'handling'
DELIVERY = 'delivery'
FINISH = 'finish'
CANCEL = 'cancel'
COD = 'cod'
ALIPAY = 'alipay'
RECOMMEND = 'recommend'
HOME = 'home'
